<?php

/**
 * Implements hook_preprocess_field().
 */
function gpx_images_preprocess_field(&$variables) {
  if($variables['element']['#formatter'] == 'gpx_images') {
    $variables['attributes']['class'] = ['gpx-images'];
    $variables['#attached']['library'][] = 'gpx_images/gpx_images.gpx_images';
  }

  $moduleHandler = \Drupal::service('module_handler');
  if ($moduleHandler->moduleExists('photoswipe')){
   // $variables['#attached']['library'][] = 'photoswipe/photoswipe';
//    $variables['#attached']['library'][] = 'photoswipe/photoswipe.init';
  }
}
