<?php

/**
 * @file
 * Contains gpx_field.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

// Include hooks
foreach (glob(__DIR__ . '/hooks/*.inc') as $file) {
    /** @noinspection PhpIncludeInspection */
    require_once $file;
}

/**
 * Implements hook_help().
 */
function gpx_field_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the gpx_field module.
    case 'help.page.gpx_field':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Create a field type for storing gpx data') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_preprocess_page().
 */
function gpx_field_preprocess_page(&$variables) {

  // Uncomment to add route name to every page
//  drupal_set_message(\Drupal::routeMatch()->getRouteName());

}

