#!/usr/bin/env bash

PROJECT_NAME="sharemyadventure"
PROJECT_HUMAN_NAME="Share My Adventure"
HOST_NAME="sharemyadventure.local"
IP="192.168.56.101"
WEBROOT="/vagrant/www"
FILES_DIR="/vagrant/www/sites/default/files"
DB_NAME="sharemyadventure"
DB_ROOT_PASS="password"
DB_USER="sma_user"
DB_HOST="localhost"
DB_PASS="password"
SITE_LOCALE="au"
ADMIN_EMAIL="dahousecat@gmail.com"
ADMIN_USERNAME="admin"
ADMIN_PASS="password"
USERNAME="vagrant"
